# Generated by Django 4.2 on 2023-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_alter_bb_options_alter_bb_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('s', 'Продам'), ('b', 'Куплю'), ('c', 'Поменяю')], default='s', max_length=1),
        ),
    ]
