# Generated by Django 4.2 on 2023-06-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_alter_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('c', 'Поменяю'), ('b', 'Куплю'), ('s', 'Продам')], default='s', max_length=1),
        ),
    ]
